# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
